<?php

// Require Helpers
require_once(drupal_get_path('module', 'cc_helper') . '/lib/ImageHelper.php');
require_once(drupal_get_path('module', 'cc_helper') . '/lib/FieldHelper.php');
require_once(drupal_get_path('module', 'cc_helper') . '/lib/ColorHelper.php');
require_once(drupal_get_path('module', 'cc_helper') . '/lib/ParagraphHelper.php');
require_once(drupal_get_path('module', 'cc_helper') . '/lib/LinkHelper.php');

/**
 * Implements hook_theme($existing, $type, $theme, $path).
 */
function cmb_jumbotron_featured_theme($existing, $type, $theme, $path) {
  $theme = array();

  $theme['paragraphs_item__cmb_jumbotron_featured'] = array(
    'template' => 'paragraphs-item--cmb_jumbotron_featured',
    'path' => drupal_get_path('module', 'cmb_jumbotron_featured') . '/templates',
  );

  // Paragraphs editor preview
  $theme['paragraphs_item__cmb_jumbotron_featured__paragraphs_editor_preview'] = array(
    'template' => 'paragraphs-item--cmb_jumbotron_featured--paragraphs_editor_preview',
    'path' => drupal_get_path('module', 'cmb_jumbotron_featured') . '/templates',
  );

  return $theme;
}

/**
 * Implements hook_preprocess_entity(&$variables).
 */
function cmb_jumbotron_featured_preprocess_entity(&$variables) {
	if ($variables['entity_type'] == 'paragraphs_item' && $variables['elements']['#bundle'] == 'cmb_jumbotron_featured') {
  	$paragraph = $variables['paragraphs_item'];

  	switch($variables['view_mode']) {
      case 'paragraphs_editor_preview':
        $data = [
          'id' => $paragraph->item_id,
        ];
        break;

      case 'full':
        // Attach css
        drupal_add_css(drupal_get_path('theme', 'cmb_theme') . '/css/cmb_theme.css');

        $data = [
          'id' => $paragraph->item_id,
          'title' => \ContentComponents\Helper\FieldHelper::getValue($paragraph, 'field_cmb_jf_title'),
          'sub_title' => \ContentComponents\Helper\FieldHelper::getValue($paragraph, 'field_cmb_jf_subtitle'),
          'image' => \ContentComponents\Helper\ImageHelper::getAttributes($paragraph, 'field_cmb_jf_image', 'cmb_jumbotron_slide', 'thumbnail'),
        ];
        break;
  	}

    //dpm($data);

    $variables['cmb_jumbotron_featured'] = $data;
  }
}
