<?php

/**
 * Implements hook_theme($existing, $type, $theme, $path).
 */
function cmb_cc_video_theme($existing, $type, $theme, $path) {
  $theme = array();

  $theme['paragraphs_item__cmb_video'] = array(
    'template' => 'paragraphs-item--cmb_video',
    'path' => drupal_get_path('module', 'cmb_cc_video') . '/templates',
  );

  // Paragraphs editor preview
  $theme['paragraphs_item__cmb_video__paragraphs_editor_preview'] = array(
    'template' => 'paragraphs-item--cmb_video--paragraphs_editor_preview',
    'path' => drupal_get_path('module', 'cmb_cc_video') . '/templates',
  );

  return $theme;
}

/**
 * Implements hook_preprocess_entity(&$variables).
 */
function cmb_cc_video_preprocess_entity(&$variables) {
	if ($variables['entity_type'] == 'paragraphs_item' && $variables['elements']['#bundle'] == 'cmb_video') {
  	$paragraph = $variables['paragraphs_item'];

  	switch($variables['view_mode']) {
      case 'paragraphs_editor_preview':
        $data = array(
          'id' => $paragraph->item_id,
        );
        break;

      case 'full':
        $data = array(
          'id' => $paragraph->item_id,
        );
        break;
  	}

    $variables['cmb_video'] = $data;
  }
}
