<?php

/**
 * Implements hook_node_info()
 * Defines content types
 */
function cm_bootstrap_archive_node_info() {
  return array(
    'archive_node_ref' => array(
      'name' => t('Archive (Node Ref)'),
      'base' => 'node_content',
      'description' => t('Archive (Node Ref) 2 column layout pages'),
      'has_title' => TRUE,
      'title_label' => t('Title')
    ),
    'archive_content_type' => array(
      'name' => t('Archive (Content Type)'),
      'base' => 'node_content',
      'description' => t('Archive (Content Type) 2 column layout pages'),
      'has_title' => TRUE,
      'title_label' => t('Title')
    ),
  );
}

/**
 * Implement hook_form()
 */
function cm_bootstrap_archive_form($node, $form_state) {
  return node_content_form($node, $form_state);
}

/**
 * Implements hook_block_info().
 */
function cm_bootstrap_archive_block_info() {  
  $blocks['cmb_archive_two_col'] = array(
    'info' => t('cm_bootstrap_archive: Archive Two Columns'),
    'cache' => DRUPAL_NO_CACHE,
    'weight' => '0',
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function cm_bootstrap_archive_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'cmb_archive_two_col':
      module_load_include('inc', 'cm_bootstrap_archive', 'blocks/cmb_archive_two_col');
      
      $block['content'] = array(
        '#markup' => _cmb_archive_two_col(),
        '#attached' => array(
          'css' => array(
            drupal_get_path('module', 'cm_bootstrap_archive') . '/css/cm_bootstrap_archive.css'
          ),
          'js' => array(
            drupal_get_path('module', 'cm_bootstrap_archive') . '/js/cm_bootstrap_archive.js'
          ),
        ),
      );      
      break;
  }   
  return $block;
}

/**
 * Implements hook_theme().
 */
function cm_bootstrap_archive_theme($existing, $type, $theme, $path) {
	$theme = array();
	$theme['cmb_archive_two_col'] = array(
		'template' => 'cmb-archive-two-col',
		'path' => $path . '/templates',
	);
	return $theme;
}
