<?php

/**
 * Implements hook_block_info().
 */
function cm_bootstrap_jumbotron_block_info() {
  $blocks['cmb_jumbotron'] = array(
    'info' => t('Jumbotron [module: cm_bootstrap_jumbotron]'),
    'cache' => DRUPAL_NO_CACHE,
    'title' => '<none>',
    'region' => 'above_content',
    'status' => TRUE,
    'weight' => 0,
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => '<front>',
  );

  return $blocks;
}

// @todo Finish this hook to force Drupal to only place
// this block for the cm_bootstrap theme.
/**
 * Implements hook_block_info_alter(&$blocks, $theme, $code_blocks).
 */
/*function cm_bootstrap_jumbotron_block_info_alter(&$blocks, $theme, $code_blocks) {
}*/

/**
 * Implements hook_block_view().
 */
function cm_bootstrap_jumbotron_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'cmb_jumbotron':
      module_load_include('inc', 'cm_bootstrap_jumbotron', 'blocks/cmb_jumbotron');
      //$block['content'] = _cmb_jumbotron();
      $block['content'] = array(
        '#markup' => _cmb_jumbotron(),
        '#attached' => array(
          'js' => array(
            drupal_get_path('module', 'cm_bootstrap_jumbotron') . '/js/cm_bootstrap_jumbotron.js',
            'scope' => 'footer',
            'weight' => -5,
          ),
          'css' => array(
            drupal_get_path('module', 'cm_bootstrap_jumbotron') . '/css/cm_bootstrap_jumbotron.css'
          ),
        ),
      );
    break;
  }
  return $block;
}

/**
 * Implements hook_theme().
 */
function cm_bootstrap_jumbotron_theme($existing, $type, $theme, $path) {
	$theme = array();
	$theme['cmb_jumbotron'] = array(
		'template' => 'cmb-jumbotron',
		'path' => $path . '/templates',
	);
	return $theme;
}

/**
 * Implements hook_image_default_styles().
 */
function cm_bootstrap_jumbotron_image_default_styles() {
  $styles = array();
  $styles['cmb_jumbotron'] = array(
    'label' => 'cmb_jumbotron)',
    'effects' => array(
      array(
        'name' => 'image_scale_and_crop',
        'data' => array(
          'width' => 1440,
          'height' => 720,
          'upscale' => 1,
        ),
        'weight' => 0,
      ),
    )
  );
  return $styles;
}
