<?php
/**
 * @file
 * cmb_jumbotron_featured_features.strongarm.inc
 */

/**
 * Implements hook_strongarm().
 */
function cmb_jumbotron_featured_features_strongarm() {
  $export = array();

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'field_bundle_settings_paragraphs_item__cmb_jumbotron_featured';
  $strongarm->value = array(
    'view_modes' => array(),
    'extra_fields' => array(
      'form' => array(
        'redirect' => array(
          'weight' => '3',
        ),
      ),
      'display' => array(),
    ),
  );
  $export['field_bundle_settings_paragraphs_item__cmb_jumbotron_featured'] = $strongarm;

  return $export;
}
