<?php
/**
 * @file
 * cmb_landing_page_features.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function cmb_landing_page_features_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'node-cmb_landing_page-field_content_components'.
  $field_instances['node-cmb_landing_page-field_content_components'] = array(
    'bundle' => 'cmb_landing_page',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'paragraphs',
        'settings' => array(
          'linked_field' => array(
            'advanced' => array(
              'class' => '',
              'rel' => '',
              'target' => '',
              'text' => '',
              'title' => '',
            ),
            'destination' => '',
            'linked' => 0,
          ),
          'view_mode' => 'full',
        ),
        'type' => 'paragraphs_view',
        'weight' => 1,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_content_components',
    'label' => 'Paragraphs',
    'required' => 0,
    'settings' => array(
      'add_mode' => 'select',
      'allowed_bundles' => array(
        'cmb_block_reference' => 'cmb_block_reference',
        'cmb_jumbotron' => 'cmb_jumbotron',
        'cmb_jumbotron_featured' => 'cmb_jumbotron_featured',
        'cmb_jumbotron_item' => -1,
        'cmb_video' => 'cmb_video',
        'cmb_video_grid' => 'cmb_video_grid',
        'content_list' => 'content_list',
        'content_list_item' => -1,
        'custom_video_list' => 'custom_video_list',
        'custom_video_list_context' => 'custom_video_list_context',
        'image' => 'image',
        'slider' => 'slider',
        'slider_item' => -1,
        'text' => 'text',
        'text_and_image' => 'text_and_image',
        'text_with_background' => 'text_with_background',
      ),
      'bundle_weights' => array(
        'cmb_block_reference' => 2,
        'cmb_jumbotron' => 3,
        'cmb_jumbotron_featured' => 28,
        'cmb_jumbotron_item' => 4,
        'cmb_video' => -32,
        'cmb_video_grid' => -32,
        'content_list' => 15,
        'content_list_item' => 16,
        'custom_video_list' => 7,
        'custom_video_list_context' => 8,
        'image' => 19,
        'slider' => 20,
        'slider_item' => 21,
        'text' => 22,
        'text_and_image' => 23,
        'text_with_background' => 24,
      ),
      'default_edit_mode' => 'open',
      'title' => 'Paragraph',
      'title_multiple' => 'Paragraphs',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'paragraphs',
      'settings' => array(),
      'type' => 'paragraphs_embed',
      'weight' => 1,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Paragraphs');

  return $field_instances;
}
