<?php

/**
 * Implements hook_theme($existing, $type, $theme, $path).
 */
function cc_text_and_video_theme($existing, $type, $theme, $path) {
  $theme = array();

  $theme['paragraphs_item__text_and_video'] = array(
    'template' => 'paragraphs-item--text-and-video',
    'path' => drupal_get_path('module', 'cc_text_and_video') . '/templates',
   );

  return $theme;
}

/**
 * Implements hook_preprocess_entity(&$variables).
 */
function cc_text_and_video_preprocess_entity(&$variables) {
	if ($variables['entity_type'] == 'paragraphs_item' && $variables['elements']['#bundle'] == 'text_and_video') {
    $paragraph = $variables['paragraphs_item'];

    $text = FALSE;
    if (isset($paragraph->field_cc_tav_text[LANGUAGE_NONE])) {
      $text = $paragraph->field_cc_tav_text[LANGUAGE_NONE][0]['value'];
    }

    // Image alignment
    $image_alignment = $paragraph->field_cc_tav_image_align[LANGUAGE_NONE][0]['value'];

    $data = array(
      'id' => $paragraph->item_id,
      'field_cc_tav_text' => $text,
      'alignment' => $image_alignment,
      'video' => $paragraph->field_cc_tav_video,
    );

    $variables['text_and_video'] = $data;
  }
}
