<?php

/**
 * Implements hook_theme($existing, $type, $theme, $path).
 */
function cmb_custom_video_list_context_theme($existing, $type, $theme, $path) {
  $theme = array();

  // Full
  $theme['paragraphs_item__custom_video_list_context'] = array(
    'template' => 'paragraphs-item--custom-video-list-context',
    'path' => drupal_get_path('module', 'cmb_custom_video_list_context') . '/templates',
  );

  // Paragraphs editor preview
  $theme['paragraphs_item__custom_video_list_context__paragraphs_editor_preview'] = array(
    'template' => 'paragraphs-item--custom-video-list-context--paragraphs_editor_preview',
    'path' => drupal_get_path('module', 'cmb_custom_video_list_context') . '/templates',
  );

  return $theme;
}

/**
 * Implements hook_preprocess_entity(&$variables).
 */
function cmb_custom_video_list_context_preprocess_entity(&$variables) {
	if ($variables['entity_type'] == 'paragraphs_item' && $variables['elements']['#bundle'] == 'custom_video_list_context') {
  	$paragraph = $variables['paragraphs_item'];

  	switch($variables['view_mode']) {

      case 'paragraphs_editor_preview':
        $data = array(
          'id' => $paragraph->item_id,
        );
        break;

      case 'full':
        // Attach CSS
        drupal_add_css(drupal_get_path('module', 'cmb_custom_video_list_context') . '/css/cmb_custom_video_list_context.css');
        // Attach JS
        drupal_add_js(drupal_get_path('module', 'cmb_custom_video_list_context') . '/js/cmb_custom_video_list_context.js');
        // Attach Flexloader
        libraries_load('flexloader');

        // Colors
        if (module_exists('cm_bootstrap_cp_colors')) {
          $colors = cm_bootstrap_cp_colors_get();

          $vs_heading_bg_color_1 = 'black';
          if (isset($colors['vs_heading_bg_color_1'])) {
            $vs_heading_bg_color_1 = $colors['vs_heading_bg_color_1'];
          }

          $vs_heading_text_color = 'white';
          if (isset($colors['vs_heading_text_color'])) {
            $vs_heading_text_color = $colors['vs_heading_text_color'];
          }
        }

        // Get context NID
        $nid = FALSE;
        $node = FALSE;

        if (isset($paragraph->field_cc_cvlc_er[LANGUAGE_NONE])) {
          $context_nid = $paragraph->field_cc_cvlc_er[LANGUAGE_NONE][0]['target_id'];
          // Load the context node.
          $context_node = node_load($context_nid);
        }

        if ($context_nid && $context_node) {
          // Switch and use different queries depending on context node type.
          switch ($context_node->type) {
            case 'cm_show':
              /*if (isset($context_node->og_group_ref[LANGUAGE_NONE])) {
                $context_nid = $context_node->og_group_ref[LANGUAGE_NONE][0]['target_id'];
                $nodes = _cmb_custom_video_list_context__shows_in_series($context_nid);
              }*/
              $nodes = FALSE;
              break;

            case 'cm_project':
              $shows_in_prefix = 'Shows in Series: ';
              $nodes = _cmb_custom_video_list_context__shows_in_series($context_nid);
              break;

            case 'genre':
              $shows_in_prefix = 'Shows in Genre: ';
              $nodes = _cmb_custom_video_list_context__shows_in_genre($context_nid);
              break;
          }

          // Start data stuff
          if ($nodes) {
            // Block title
            $title = $shows_in_prefix . '"' . $context_node->title . '"';
            if (isset($paragraph->field_cc_cvlc_title[LANGUAGE_NONE])) {
              $title = $paragraph->field_cc_cvlc_title[LANGUAGE_NONE][0]['value'];
            }

            foreach($nodes as $node) {
              // Image, switch to account for cloudcast, vimeo, youtube, etc.
              if (isset($node->field_show_vod[LANGUAGE_NONE])) {
                switch($node->field_show_vod[LANGUAGE_NONE][0]['filemime']) {
                  case 'video/cloudcast':
                    $image_uri = 'media-cloudcast/' . $node->field_show_vod[LANGUAGE_NONE][0]['filename']  . '.jpg';
                    break;
                  case 'video/vimeo':
                    $image_uri = str_replace('vimeo://v/', 'media-vimeo/', $node->field_show_vod[LANGUAGE_NONE][0]['uri']);
                    $image_uri = $image_uri . '.jpg';
                    break;
                  case 'video/youtube':
                    $image_uri = str_replace('youtube://v/', 'media-youtube/', $node->field_show_vod[LANGUAGE_NONE][0]['uri']);
                    $image_uri = $image_uri . '.jpg';
                    break;
                  case 'video/bliptv':
                    $image_uri = str_replace('bliptv://i/BiCities-AubreyThornvoldReconcilingWorksFilmed201502703.png/v/', 'media-bliptv/', $node->field_show_vod[LANGUAGE_NONE][0]['uri']);
                    $image_uri = $image_uri . '.jpg';
                    break;
                }
                $img_src = image_style_url('500x281', $image_uri);
              }
              else {
                if (module_exists('cm_bootstrap_cp_default_images')) {
                  $file = cm_bootstrap_cp_default_images_load_image($node->type);
                  $image_uri = $file->uri;
                  $img_src = image_style_url('500x281', $image_uri);
                }
              }

              // Placeholder image
              $placeholder_img = "data:image/svg+xml;charset=utf-8,<svg%20xmlns%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%20width%3D'500'%20height%3D'281'><rect%20width%3D'100%25'%20height%3D'100%25'%20fill%3D'whitesmoke'%2F><%2Fsvg>";

              // Series title
              $series_title = FALSE;
              if (isset($node->og_group_ref[LANGUAGE_NONE])) {
                $nid = $node->og_group_ref[LANGUAGE_NONE][0]['target_id'];
                $series_title = db_query("SELECT title FROM {node} WHERE nid = :nid", array(':nid' => $nid))->fetchField();
              }

              // Description
              $description = FALSE;
              $allowable_tags = '<i>';
              if (isset($node->field_description[LANGUAGE_NONE])) {
                $description = strip_tags($node->field_description[LANGUAGE_NONE][0]['value'], $allowable_tags);
                $description = cmb_helper_truncate($description, $length = 125, array('html' => true, 'ending' => ' . . .', 'exact' => FALSE));
              }

              // Build data array for TPL
              $items[$node->nid] = array(
                'nid' => $node->nid,
                'title' => $node->title,
                'description' => $description,
                'series_title' => $series_title,
                'img_src' => $img_src,
                'placeholder_img' => $placeholder_img,
                'url' => url('node/' . $node->nid),
              );
            }
          }
        }

        $data = array(
          'id' => $paragraph->item_id,
          'title' => $title,
          'bg_color' => $vs_heading_bg_color_1,
          'text_color' => $vs_heading_text_color,
          'items' => $items,
        );
        break;
    }

    $variables['custom_video_list_context'] = $data;
  }
}

/**
 * Shows in Series Query
 */
function _cmb_custom_video_list_context__shows_in_series($nid) {
  // Data query
  $query = new EntityFieldQuery();
    $query->entityCondition('entity_type', 'node');
    $query->entityCondition('bundle', 'cm_show');
    $query->propertyCondition('status', 1);
    $query->range(0, 100);
    $query->propertyOrderBy('created', 'DESC');
    $query->fieldCondition('og_group_ref', 'target_id', $nid, '=');
  $result = $query->execute();

  //
  if (isset($result['node'])) {
    $nids = array_keys($result['node']);
    $nodes = entity_load('node', $nids);
  }
  else {
    $nodes = FALSE;
  }

  return $nodes;
}

/**
 * Shows in Genre Query
 */
function _cmb_custom_video_list_context__shows_in_genre($nid) {
  // Get all shows tagged with current node 'genre'.
  $query = new EntityFieldQuery();
    $query->entityCondition('entity_type', 'node');
    $query->entityCondition('bundle', 'cm_show');
    $query->propertyCondition('status', 1);
    $query->fieldCondition('field_genres', 'target_id', $nid, '=');
    $query->range(0, 25);
    $query->propertyOrderBy('created', 'DESC');
  $result = $query->execute();

  if (isset($result['node'])) {
    $nids = array_keys($result['node']);
    $nodes = entity_load('node', $nids);
  }
  else {
    $nodes = FALSE;
  }

  return $nodes;
}
