<?php

/**
 * Implements hook_views_api().
 */
function cm_bootstrap_search_views_api() {
  return array(
    'api' => 3,
  );
}

/**
 * Implements hook_form_alter(&$form, &$form_state, $form_id).
 */
function cm_bootstrap_search_form_alter(&$form, &$form_state, $form_id) {	
	if (($form_id == 'views_exposed_form') && ($form['#id'] == 'views-exposed-form-solr-search-page')) {
		// Change to checkboxes
		$form['node_type']['#type'] = 'checkboxes';
		$form['node_type']['#default_value']['page'] = 1;
		//dpm($form);
  }
  else if (($form_id == 'views_exposed_form') && ($form['#id'] =='views-exposed-form-solr-search-block-1')) {
    $form['node_type']['#type'] = 'checkboxes';
  }  
}
